import { TaskTemplate } from '@/types';

export const taskTemplates: TaskTemplate[] = [
  {
    id: 'writing',
    title: 'Writing & Content Creation',
    description: 'Generate prompts for essays, articles, blog posts, and creative writing',
    icon: '✍️',
    questions: [
      {
        id: 'topic',
        type: 'text',
        label: 'What is the main topic or subject?',
        placeholder: 'e.g., Climate change, Product reviews, Personal experiences',
        required: true,
      },
      {
        id: 'purpose',
        type: 'select',
        label: 'What is the purpose of this writing?',
        required: true,
        options: ['Inform/Educate', 'Persuade/Convince', 'Entertain', 'Express Opinion', 'Tell a Story', 'Review/Analyze'],
      },
      {
        id: 'audience',
        type: 'text',
        label: 'Who is your target audience?',
        placeholder: 'e.g., General public, Students, Professionals, Children',
        required: true,
      },
      {
        id: 'tone',
        type: 'select',
        label: 'What tone should the writing have?',
        required: true,
        options: ['Formal', 'Casual', 'Professional', 'Friendly', 'Authoritative', 'Conversational', 'Humorous'],
      },
      {
        id: 'length',
        type: 'select',
        label: 'Approximate length?',
        required: true,
        options: ['Short (1-2 paragraphs)', 'Medium (3-5 paragraphs)', 'Long (6+ paragraphs)', 'Article length (1000+ words)'],
      },
      {
        id: 'key_points',
        type: 'textarea',
        label: 'What are the key points or arguments to include?',
        placeholder: 'List the main ideas, arguments, or points you want to cover...',
        required: false,
      },
      {
        id: 'style_requirements',
        type: 'multiselect',
        label: 'Any specific style requirements?',
        required: false,
        options: ['Include examples', 'Use data/statistics', 'Include quotes', 'First-person perspective', 'Third-person perspective', 'Include call-to-action'],
      },
    ],
  },
  {
    id: 'coding',
    title: 'Programming & Development',
    description: 'Create prompts for coding tasks, debugging, and technical problem-solving',
    icon: '💻',
    questions: [
      {
        id: 'language',
        type: 'select',
        label: 'What programming language?',
        required: true,
        options: ['JavaScript/TypeScript', 'Python', 'Java', 'C++', 'C#', 'Go', 'Rust', 'PHP', 'Ruby', 'Swift', 'Kotlin', 'Other'],
      },
      {
        id: 'task_type',
        type: 'select',
        label: 'What type of coding task?',
        required: true,
        options: ['Write new code', 'Debug existing code', 'Optimize performance', 'Refactor code', 'Add new features', 'Fix bugs', 'Code review', 'Architecture design'],
      },
      {
        id: 'problem_description',
        type: 'textarea',
        label: 'Describe the problem or task in detail',
        placeholder: 'Explain what you need to accomplish, any constraints, or specific requirements...',
        required: true,
      },
      {
        id: 'framework',
        type: 'text',
        label: 'Any specific framework or library?',
        placeholder: 'e.g., React, Django, Spring Boot, Express.js',
        required: false,
      },
      {
        id: 'complexity',
        type: 'select',
        label: 'What is the complexity level?',
        required: true,
        options: ['Beginner', 'Intermediate', 'Advanced', 'Expert'],
      },
      {
        id: 'constraints',
        type: 'multiselect',
        label: 'Any specific constraints or requirements?',
        required: false,
        options: ['Time complexity optimization', 'Memory efficiency', 'Security considerations', 'Scalability', 'Maintainability', 'Testing requirements', 'Documentation needed'],
      },
      {
        id: 'existing_code',
        type: 'textarea',
        label: 'Existing code or context (if applicable)',
        placeholder: 'Paste any relevant existing code or provide context...',
        required: false,
      },
    ],
  },
  {
    id: 'data_analysis',
    title: 'Data Analysis & Research',
    description: 'Generate prompts for data analysis, research, and statistical work',
    icon: '📊',
    questions: [
      {
        id: 'data_type',
        type: 'select',
        label: 'What type of data are you working with?',
        required: true,
        options: ['Numerical/Statistical', 'Text/NLP', 'Time Series', 'Categorical', 'Mixed/Complex', 'Survey Data', 'Financial Data', 'Scientific Data'],
      },
      {
        id: 'analysis_goal',
        type: 'select',
        label: 'What is your primary analysis goal?',
        required: true,
        options: ['Descriptive Analysis', 'Predictive Modeling', 'Hypothesis Testing', 'Pattern Recognition', 'Trend Analysis', 'Correlation Analysis', 'Classification', 'Clustering'],
      },
      {
        id: 'dataset_description',
        type: 'textarea',
        label: 'Describe your dataset',
        placeholder: 'Size, variables, data quality, source, any known issues...',
        required: true,
      },
      {
        id: 'tools',
        type: 'multiselect',
        label: 'What tools or software are you using?',
        required: false,
        options: ['Python (pandas, numpy)', 'R', 'Excel', 'SQL', 'Tableau', 'Power BI', 'SPSS', 'MATLAB', 'Jupyter Notebooks'],
      },
      {
        id: 'hypothesis',
        type: 'textarea',
        label: 'Any specific hypotheses or questions to test?',
        placeholder: 'What are you trying to prove or discover?',
        required: false,
      },
      {
        id: 'output_format',
        type: 'select',
        label: 'What format do you need the results in?',
        required: true,
        options: ['Report/Summary', 'Visualizations', 'Code/Scripts', 'Statistical Output', 'Presentation', 'Dashboard'],
      },
      {
        id: 'audience',
        type: 'text',
        label: 'Who will use these results?',
        placeholder: 'e.g., Management, Researchers, Clients, General public',
        required: false,
      },
    ],
  },
  {
    id: 'brainstorming',
    title: 'Brainstorming & Ideation',
    description: 'Create prompts for creative brainstorming and idea generation',
    icon: '💡',
    questions: [
      {
        id: 'challenge',
        type: 'textarea',
        label: 'What challenge or problem are you trying to solve?',
        placeholder: 'Describe the challenge, opportunity, or goal you want to brainstorm around...',
        required: true,
      },
      {
        id: 'context',
        type: 'select',
        label: 'What is the context or domain?',
        required: true,
        options: ['Business/Startup', 'Product Development', 'Marketing', 'Technology', 'Education', 'Healthcare', 'Creative/Arts', 'Social Impact', 'Personal', 'Other'],
      },
      {
        id: 'constraints',
        type: 'multiselect',
        label: 'What are the main constraints?',
        required: false,
        options: ['Budget limitations', 'Time constraints', 'Technical limitations', 'Regulatory requirements', 'Market conditions', 'Resource availability', 'Team size'],
      },
      {
        id: 'target_audience',
        type: 'text',
        label: 'Who is the target audience or user?',
        placeholder: 'e.g., Young professionals, Small businesses, Students, Elderly',
        required: false,
      },
      {
        id: 'innovation_level',
        type: 'select',
        label: 'How innovative should the ideas be?',
        required: true,
        options: ['Incremental improvements', 'Moderate innovation', 'Breakthrough ideas', 'Completely revolutionary', 'Mix of all levels'],
      },
      {
        id: 'timeframe',
        type: 'select',
        label: 'What is the implementation timeframe?',
        required: false,
        options: ['Immediate (1-3 months)', 'Short-term (3-12 months)', 'Medium-term (1-2 years)', 'Long-term (2+ years)', 'No specific timeline'],
      },
      {
        id: 'success_metrics',
        type: 'textarea',
        label: 'How will you measure success?',
        placeholder: 'What metrics or outcomes would indicate a successful solution?',
        required: false,
      },
    ],
  },
  {
    id: 'research',
    title: 'Research & Information Gathering',
    description: 'Generate prompts for research tasks and information synthesis',
    icon: '🔍',
    questions: [
      {
        id: 'research_topic',
        type: 'text',
        label: 'What is your research topic or question?',
        placeholder: 'e.g., Impact of remote work on productivity, Latest trends in AI',
        required: true,
      },
      {
        id: 'research_type',
        type: 'select',
        label: 'What type of research?',
        required: true,
        options: ['Literature Review', 'Market Research', 'Competitive Analysis', 'Technical Research', 'Historical Research', 'Case Study', 'Survey Research', 'Trend Analysis'],
      },
      {
        id: 'scope',
        type: 'select',
        label: 'What is the scope of your research?',
        required: true,
        options: ['Broad overview', 'Specific focus area', 'Comparative analysis', 'Deep dive into one aspect', 'Multi-faceted approach'],
      },
      {
        id: 'sources',
        type: 'multiselect',
        label: 'What types of sources do you need?',
        required: false,
        options: ['Academic papers', 'Industry reports', 'News articles', 'Government data', 'Company websites', 'Social media', 'Expert interviews', 'Statistical data'],
      },
      {
        id: 'timeframe',
        type: 'select',
        label: 'What time period should the research cover?',
        required: false,
        options: ['Current/recent (last 1-2 years)', 'Historical (5+ years)', 'Trend analysis (3-5 years)', 'All available data', 'Specific time period'],
      },
      {
        id: 'output_format',
        type: 'select',
        label: 'What format do you need the research in?',
        required: true,
        options: ['Summary report', 'Detailed analysis', 'Presentation', 'Executive brief', 'Literature review', 'Data compilation', 'Comparative table'],
      },
      {
        id: 'key_findings',
        type: 'textarea',
        label: 'Any specific aspects or findings you want to focus on?',
        placeholder: 'What particular insights or information are you looking for?',
        required: false,
      },
    ],
  },
  {
    id: 'learning',
    title: 'Learning & Education',
    description: 'Create prompts for educational content and learning experiences',
    icon: '🎓',
    questions: [
      {
        id: 'subject',
        type: 'text',
        label: 'What subject or topic do you want to learn about?',
        placeholder: 'e.g., Machine Learning, History of Art, Financial Planning',
        required: true,
      },
      {
        id: 'learning_goal',
        type: 'select',
        label: 'What is your learning goal?',
        required: true,
        options: ['Basic understanding', 'Intermediate knowledge', 'Advanced expertise', 'Practical application', 'Theoretical foundation', 'Skill development', 'Exam preparation'],
      },
      {
        id: 'current_level',
        type: 'select',
        label: 'What is your current knowledge level?',
        required: true,
        options: ['Complete beginner', 'Some familiarity', 'Intermediate', 'Advanced', 'Expert (wanting to deepen)'],
      },
      {
        id: 'learning_style',
        type: 'multiselect',
        label: 'What learning styles work best for you?',
        required: false,
        options: ['Visual (diagrams, charts)', 'Reading (text-based)', 'Hands-on practice', 'Examples and cases', 'Step-by-step tutorials', 'Interactive exercises', 'Video content'],
      },
      {
        id: 'time_available',
        type: 'select',
        label: 'How much time can you dedicate?',
        required: false,
        options: ['Quick overview (30 minutes)', 'Short session (1-2 hours)', 'Moderate study (1-2 weeks)', 'Intensive learning (1+ months)', 'Flexible schedule'],
      },
      {
        id: 'practical_application',
        type: 'textarea',
        label: 'How do you plan to apply this knowledge?',
        placeholder: 'Describe your intended use case or application...',
        required: false,
      },
      {
        id: 'specific_areas',
        type: 'textarea',
        label: 'Any specific areas or subtopics to focus on?',
        placeholder: 'List particular aspects you want to emphasize or avoid...',
        required: false,
      },
    ],
  },
  {
    id: 'creative',
    title: 'Creative Projects',
    description: 'Generate prompts for creative writing, design, and artistic endeavors',
    icon: '🎨',
    questions: [
      {
        id: 'creative_type',
        type: 'select',
        label: 'What type of creative project?',
        required: true,
        options: ['Creative Writing', 'Visual Design', 'Music/Composition', 'Art/Craft', 'Photography', 'Video/Film', 'Performance', 'Game Design', 'Other'],
      },
      {
        id: 'theme',
        type: 'text',
        label: 'What is the main theme or concept?',
        placeholder: 'e.g., Nature, Technology, Love, Adventure, Mystery',
        required: true,
      },
      {
        id: 'mood',
        type: 'select',
        label: 'What mood or atmosphere?',
        required: true,
        options: ['Uplifting', 'Melancholic', 'Mysterious', 'Romantic', 'Dramatic', 'Playful', 'Serious', 'Nostalgic', 'Futuristic', 'Natural'],
      },
      {
        id: 'audience',
        type: 'text',
        label: 'Who is the intended audience?',
        placeholder: 'e.g., Children, Adults, Art enthusiasts, General public',
        required: false,
      },
      {
        id: 'style',
        type: 'select',
        label: 'What style or approach?',
        required: false,
        options: ['Modern', 'Classic', 'Abstract', 'Realistic', 'Minimalist', 'Maximalist', 'Experimental', 'Traditional', 'Contemporary'],
      },
      {
        id: 'constraints',
        type: 'multiselect',
        label: 'Any creative constraints or requirements?',
        required: false,
        options: ['Limited materials', 'Time constraints', 'Size limitations', 'Color restrictions', 'Format requirements', 'Budget constraints', 'Technical limitations'],
      },
      {
        id: 'inspiration',
        type: 'textarea',
        label: 'Any specific inspiration or references?',
        placeholder: 'Describe artists, works, or ideas that inspire you...',
        required: false,
      },
    ],
  },
  {
    id: 'business',
    title: 'Business & Strategy',
    description: 'Create prompts for business planning, strategy, and professional tasks',
    icon: '💼',
    questions: [
      {
        id: 'business_type',
        type: 'select',
        label: 'What type of business activity?',
        required: true,
        options: ['Business Plan', 'Marketing Strategy', 'Financial Analysis', 'Operations Planning', 'HR Strategy', 'Product Development', 'Market Research', 'Competitive Analysis'],
      },
      {
        id: 'company_stage',
        type: 'select',
        label: 'What stage is your company in?',
        required: true,
        options: ['Startup/Idea stage', 'Early stage', 'Growth stage', 'Mature/Established', 'Expansion', 'Turnaround', 'Not applicable'],
      },
      {
        id: 'industry',
        type: 'text',
        label: 'What industry or sector?',
        placeholder: 'e.g., Technology, Healthcare, Retail, Manufacturing, Services',
        required: true,
      },
      {
        id: 'target_market',
        type: 'text',
        label: 'Who is your target market?',
        placeholder: 'Describe your ideal customers or market segment...',
        required: false,
      },
      {
        id: 'goals',
        type: 'textarea',
        label: 'What are your main business goals?',
        placeholder: 'Describe your primary objectives and desired outcomes...',
        required: true,
      },
      {
        id: 'challenges',
        type: 'multiselect',
        label: 'What are your main challenges?',
        required: false,
        options: ['Funding/Capital', 'Market competition', 'Customer acquisition', 'Product development', 'Team building', 'Operational efficiency', 'Regulatory compliance', 'Technology adoption'],
      },
      {
        id: 'timeline',
        type: 'select',
        label: 'What is your planning timeline?',
        required: false,
        options: ['Immediate (1-3 months)', 'Short-term (3-12 months)', 'Medium-term (1-2 years)', 'Long-term (2+ years)', 'Strategic planning (3-5 years)'],
      },
    ],
  },
];

export const getTemplateById = (id: string): TaskTemplate | undefined => {
  return taskTemplates.find(template => template.id === id);
};
